# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish
      run: dotnet publish --no-restore 

    - name: Zip build artifacts
      uses: OctopusDeploy/create-zip-package-action@v3.0.2
      with:
        package_id: Revue
        version: "1.0.$((GITHUB_RUN_NUMBER))"
        base_path: ./bin/Release/net8.0/publish/
        files: |
         **/*
        output_folder: ./output

    - name: Publish build artifacts
      uses: actions/upload-artifact@v7
      with:
        name: revue-webapp
        path: ./output/Revue.1.0.$((GITHUB_RUN_NUMBER)).zip

    # Create GitHub Release (if we want)
